"""
Threat Report Generator — Developer Advocate replacement.

Generates weekly threat intelligence reports from your live API data.
Output is formatted for LinkedIn/Twitter posts or GitHub discussions.

Run:
    python -m agents.threat_report

Output: Markdown report ready to paste on LinkedIn/GitHub.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime

import httpx

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [ReportAgent] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

API_URL = "https://sentinelx402-production.up.railway.app"


async def gather_data() -> dict:
    """Gather data from the live API for the report."""
    data = {}
    async with httpx.AsyncClient(timeout=15) as client:
        # Stats
        resp = await client.get("{}/stats".format(API_URL))
        data["stats"] = resp.json()

        # Top threats from feed
        resp = await client.get("{}/api/v1/threats/feed?page=1&page_size=10".format(API_URL))
        data["top_threats"] = resp.json()

        # Recent CVEs
        try:
            resp = await client.get("{}/api/v1/cves/recent?limit=5".format(API_URL))
            data["recent_cves"] = resp.json()
        except Exception:
            data["recent_cves"] = {"cves": []}

        # Test some high-profile domains
        test_domains = [
            "login-secure-paypal.com",
            "metamask-wallet-sync.com",
            "sbi-online-banking-verify.com",
        ]
        data["sample_detections"] = []
        for domain in test_domains:
            resp = await client.get("{}/api/v1/threats/lookup".format(API_URL), params={"domain": domain})
            data["sample_detections"].append(resp.json())

    return data


def generate_linkedin_post(data: dict) -> str:
    """Generate a LinkedIn-ready threat report post."""
    stats = data["stats"]
    coverage = stats.get("data_coverage", {})
    total_indicators = coverage.get("total_indicators", 0)
    clients = stats.get("usage", {}).get("total_clients", 0)

    threats = data["top_threats"].get("indicators", [])
    cves = data["recent_cves"].get("cves", [])

    post = """This week's threat intelligence snapshot from SentinelX402:

Monitoring {} live threat indicators across 3 feeds.

Top threats detected this week:
""".format(total_indicators)

    for t in threats[:5]:
        post += "- {} ({}, score: {})\n".format(t["value"], t["threat_type"], t["risk_score"])

    if cves:
        post += "\nCritical CVEs this week:\n"
        for c in cves[:3]:
            post += "- {} (CVSS {}, exploit prob: {})\n".format(c["cve_id"], c["cvss"], c["exploit_probability"])

    post += """
Data sources: OpenPhish, Feodo Tracker, URLhaus, NVD

Free to use — 1,000 requests, no signup:
https://sentinelx402-production.up.railway.app

#cybersecurity #threatintelligence #AI #agents"""

    return post


def generate_github_report(data: dict) -> str:
    """Generate a GitHub discussion-ready weekly report."""
    stats = data["stats"]
    coverage = stats.get("data_coverage", {})
    today = datetime.utcnow().strftime("%Y-%m-%d")

    report = """# Weekly Threat Intelligence Report — {}

## Coverage Summary

| Source | Indicators |
|--------|-----------|
| OpenPhish (phishing) | {} |
| Feodo Tracker (C2) | {} |
| URLhaus (malware) | {} |
| Local IOCs | {} |
| **Total** | **{}** |

## Top Threats This Week

""".format(
        today,
        coverage.get("live_phishing_urls", 0),
        coverage.get("live_c2_ips", 0),
        coverage.get("live_malware_urls", 0),
        coverage.get("local_iocs", 0),
        coverage.get("total_indicators", 0),
    )

    for t in data["top_threats"].get("indicators", [])[:10]:
        report += "| `{}` | {} | score: {} |\n".format(t["value"], t["threat_type"], t["risk_score"])

    cves = data["recent_cves"].get("cves", [])
    if cves:
        report += "\n## Critical CVEs\n\n"
        for c in cves[:5]:
            report += "- **{}** — CVSS {} | {} | exploit prob: {}\n".format(
                c["cve_id"], c["cvss"], c["risk"], c["exploit_probability"]
            )

    report += """
---

*Generated by SentinelX402 Threat Report Agent*
*Try the API: https://sentinelx402-production.up.railway.app*
"""
    return report


async def main():
    logger.info("Generating threat report...")
    data = await gather_data()

    linkedin = generate_linkedin_post(data)
    github = generate_github_report(data)

    print("\n" + "=" * 60)
    print("LINKEDIN POST")
    print("=" * 60)
    print(linkedin)

    print("\n" + "=" * 60)
    print("GITHUB REPORT")
    print("=" * 60)
    print(github)

    # Save to files
    from pathlib import Path
    out = Path(__file__).parent
    (out / "latest_linkedin_post.md").write_text(linkedin)
    (out / "latest_github_report.md").write_text(github)
    logger.info("Reports saved to agents/ directory")


if __name__ == "__main__":
    asyncio.run(main())
